# permissions for end users to edit vaultsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultsecret-editor-role
rules:
- apiGroups:
  - xo.90poe.io
  resources:
  - vaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xo.90poe.io
  resources:
  - vaultsecrets/status
  verbs:
  - get
