# permissions for end users to edit vaultcertificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vaultcertificate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vault-secrets-operator
    app.kubernetes.io/part-of: vault-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: vaultcertificate-editor-role
rules:
- apiGroups:
  - xo.90poe.io
  resources:
  - vaultcertificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xo.90poe.io
  resources:
  - vaultcertificates/status
  verbs:
  - get
