apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: vault-secrets-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: VaultSecret is the Schema for the vaultsecrets API
      displayName: Vault Secret
      kind: VaultSecret
      name: vaultsecrets.xo.90poe.io
      version: v1alpha1
  description: Vault secrets operator
  displayName: vault-secrets-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - vault
  - secrets
  links:
  - name: Vault Secrets Operator
    url: https://vault-secrets-operator.domain
  maintainers:
  - email: sarunas.krisciukaitis@90poe.io
    name: Sarunas Krisciukaitis
  maturity: alpha
  provider:
    name: 90poe
    url: https://90poe.io
  version: 0.0.0
