---
apiVersion: xo.90poe.io/v1alpha1
kind: VaultSecret
metadata:
  name: kafkaobjects-operators-secret
  namespace: infra
  labels:
    app: kafkaobjects-operator
spec:
  name: kafkaobjects-operators-secret
  reread_intervals: 3600
  type: Opaque
  secrets_paths:
    slack-token: devops/xo-dev-slack-channel-token
