{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "vault-secrets-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
    {{- with .Values.operator.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "vault-secrets-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
  {{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
