{{- $sm := .Values.serviceMonitor }}
{{- if or $sm.create -}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "vault-secrets-operator.labels" . | nindent 4 }}
    app: vault-secrets-operator
    app.kubernetes.io/component: vault-secrets-operator
    {{- with $sm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "vault-secrets-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.operator.metricsPort }}
    targetPort: {{ .Values.operator.metricsPort }}
  selector:
    app: vault-secrets-operator
    app.kubernetes.io/component: vault-secrets-operator
status:
  loadBalancer: {}
{{- end }}