name: pr_check vault-secrets-operator

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'helm/**'
      - '.github/**'
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ci-tests-${{ inputs.git_repo }}-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install latest major GO version
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26' # The Go version to download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          version: 'v2.10'
          working-directory: '.'
          args: --allow-parallel-runners -v --timeout 5m
          skip-pkg-cache: true
          skip-build-cache: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install latest major GO version
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26' # The Go version to download

      - name: Build executables locally
        run: |
          make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Dockerise
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: ./
          builder: ${{ steps.buildx.outputs.name }}
          platforms: 'linux/amd64,linux/arm64'
          tags: vault-secrets-operator:dev
          file: Dockerfile
          push: false

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install latest major GO version
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26' # The Go version to download

      - name: Test locally
        run:
          make test
