name: pr_check vault-secrets-operator

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'helm/**'
      - '.github/**'
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ci-tests-${{ inputs.git_repo }}-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install latest major GO version
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.26' # The Go version to download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          version: 'v2.10'
          working-directory: '.'
          args: --allow-parallel-runners -v --timeout 5m
          skip-pkg-cache: true
          skip-build-cache: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install latest major GO version
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.26' # The Go version to download

      - name: Build executables locally
        run: |
          make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Login to DockerHub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Dockerise
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: ./
          builder: ${{ steps.buildx.outputs.name }}
          platforms: 'linux/amd64,linux/arm64'
          tags: vault-secrets-operator:dev
          file: Dockerfile
          push: false

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install latest major GO version
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.26' # The Go version to download

      - name: Test locally
        run:
          make test
