name: pr_check vault-secrets-operator

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'helm/**'
      - '.github/**'
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ci-tests-${{ inputs.git_repo }}-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install latest major GO version
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: '1.21' # The Go version to download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3
        with:
          version: 'v1.54'
          working-directory: '.'
          args: --allow-parallel-runners -v --timeout 5m
          skip-pkg-cache: true
          skip-build-cache: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install latest major GO version
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: '1.21' # The Go version to download

      - name: Build executables locally
        run: |
          make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Dockerise
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: ./
          builder: ${{ steps.buildx.outputs.name }}
          platforms: 'linux/amd64,linux/arm64'
          tags: vault-secrets-operator:dev
          file: Dockerfile
          push: false

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install latest major GO version
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: '1.21' # The Go version to download

      - name: Test locally
        run:
          make test
